name: Build and Release (rockchip armv8)

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PACKAGE_NAME: luci-app-xray
  CACHE_DIR: ~/cache

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: rockchip_armv8
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.1/targets/rockchip/armv8
            sdk_name: -sdk-24.10.1-rockchip-armv8_

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      CCACHE_DIR: ~/.ccache
      CONFIG_CCACHE: y
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Cache Key
        id: cache_key
        run: echo "timestamp=$(date +'%s')" >> $GITHUB_OUTPUT

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CACHE_DIR }}
            ${{ env.CCACHE_DIR }}
          key: openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-${{ steps.cache_key.outputs.timestamp }}
          restore-keys: |
            openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache gettext libncurses5-dev xsltproc p7zip-full wget file zstd


      - name: Create Directories
        run: |
          CACHE_DIR_SDK="$(eval echo "$CACHE_DIR/sdk")"
          CACHE_DIR_DL="$(eval echo "$CACHE_DIR/dl")"
          CACHE_DIR_FEEDS="$(eval echo "$CACHE_DIR/feeds")"
          mkdir -p "$CACHE_DIR_SDK" "$CACHE_DIR_DL" "$CACHE_DIR_FEEDS"
          echo "CACHE_DIR_SDK=$CACHE_DIR_SDK" >> $GITHUB_ENV
          echo "CACHE_DIR_DL=$CACHE_DIR_DL" >> $GITHUB_ENV
          echo "CACHE_DIR_FEEDS=$CACHE_DIR_FEEDS" >> $GITHUB_ENV
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Download and Unpack SDK
        run: |
          cd "$CACHE_DIR_SDK"
          wget -q -O sha256sums "$SDK_URL_PATH/sha256sums"
          grep -- "$SDK_NAME" sha256sums > sha256sums.small
          SDK_FILE="$(awk '{print $2}' sha256sums.small | sed 's/*//g')"
          if [ ! -f "$SDK_FILE" ] || ! sha256sum -c sha256sums.small >/dev/null 2>&1; then
            wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
          fi
          sha256sum -c sha256sums.small

          # Распаковка .tar.zst с помощью unzstd + tar
          echo "Extracting $SDK_FILE..."
          mkdir -p "$SDK_HOME"
          unzstd -c "$SDK_FILE" | tar -C "$SDK_HOME" -xvf -

          cd "$SDK_HOME"
          ln -sf "$CACHE_DIR_DL" dl
          ln -sf "$CACHE_DIR_FEEDS" feeds
          cp feeds.conf.default feeds.conf
          sed -i 's#git.openwrt.org#github.com/openwrt#' feeds.conf
          cd -

      - name: Update and Install Feeds
        run: |
          cd "$SDK_HOME"
          ./scripts/feeds update -a
          ln -s "${{ github.workspace }}" "package/${PACKAGE_NAME}"
          ./scripts/feeds install -a
          cd -

      - name: Build Packages
        run: |
          cd "$SDK_HOME"
          make defconfig
          make package/${PACKAGE_NAME}/compile V=s
          find bin/ -type f -name "*.ipk" -exec ls -lh {} \;
          cd -

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-ipks
          path: |
            ${{ env.SDK_HOME }}/bin/packages/
            ${{ env.SDK_HOME }}/bin/targets/

  notify:
    name: Notify Release Publish
    runs-on: ubuntu-latest
    env:
      TRIGGER_URL: ${{ secrets.TRIGGER_URL }}
      TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
    needs: release
    steps:
      - name: Notify Jenkins
        run: |
          if [ -z "$TRIGGER_URL" ] ; then
            echo "No trigger URL found, skipping."
            exit 0
          fi
          curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $TRIGGER_TOKEN" \
              -d "{\"event\":\"release\",\"repository\":\"${{ github.repository }}\",\"ref\":\"${{ github.ref }}\"}" \
              "$TRIGGER_URL" || true
